### ISSUE TITLE
Small issue with README.md

### ISSUE THREAD

**Issue by ybastide** [jbbarth/webflow#2]
"Google BigQuery on the other hand doesn't provide any listing/stats capabilities out of the
box, the console only allows to browse tables and make some queries."

Not really true: there's the jobs list API, available via https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/list or https://developers.google.com/apis-explorer/#p/bigquery/v2/bigquery.jobs.list :wink: 

But I haven't been able to list the jobs I wanted: "Lists all jobs that you started in the specified project. Job information is available for a six month period after creation. The job list is sorted in reverse chronological order, by job creation time." ... It starts at a random date :confused: 

Otherwise, great job!

**Comment by ybastide** [comment]
(Err, dunno why the API was returning strange results; it works as expected now... Whivh is nice since webflow uses the same)

**Comment by jbbarth** [comment]
Hm yes I understand the issue with the first sentence. I meant Google doesn't provide a UI for this, of course there's this API which is what webflow uses internally to synchronize jobs. I will change the phrasing.
